### ISSUE TITLE
Mollie components does not work with the Mollie integration and Pronamic-pay plug-in

### ISSUE THREAD

**Issue by asands1** [pronamic/wp-pronamic-pay#383] opened 2024-08-05 14:30 UTC
Hello, 

My name is Amy from Mollie Tech Support help.

A shared customer of ours is having trouble loading Mollie Component's.

Merchant is using Pronamic-pay plug-in with Mollie as a payment gateway.

Customer tries to pay for product with credit card and see's the components fields loading in a forever loop. 

How to reproduce issue:

1. Checkout with the product https://www.lrcb.nl/product/beeldenboek-oog-voor-verbetering/ 
2. Right click> Inspect the components field 
3. Request URL:
https://js.mollie.com/v1/controller/?profileId=pfl_xxxxxxxx&locale=nl_NL&testMode=false&hostname=www.lrcb.nl&isCoBrandedCardSupported=false
Referrer Policy:
strict-origin-when-cross-origin

Status: (Cancelled)
4. Components fields loop on forever and do not load

Integration:  PronamicPay/9.11.0 uap/FyuVeDDqnKdzdry7 WordPress/6.5.5; https://www.lrcb.nl

https://docs.mollie.com/docs/mollie-components

As we do not own the integration or have access to the source code, we can not troubleshoot the issue or offer support to the customer. 

Could you please help this customer?

**Comment by rvdsteege** [comment] 2024-08-05 14:56
We sure want to assist our customers. Our integration of Mollie Components is based on the instructions provided in https://docs.mollie.com/docs/mollie-components and we're not seeing the issue on other sites.

Our source code is available at https://github.com/pronamic/wp-pronamic-pay-mollie and the specific parts of interest:
- https://github.com/pronamic/wp-pronamic-pay-mollie/blob/8c5e8d449da4dcd0ffe08c72c62131f8f660c80f/src/ScriptsController.php#L52-L103
- https://github.com/pronamic/wp-pronamic-pay-mollie/blob/8c5e8d449da4dcd0ffe08c72c62131f8f660c80f/assets/src/wc-legacy-checkout.js

As the "forever loading loop" is occurring in the Mollie Components code, can you please elaborate a bit on when such a loop can occur in your code? We were unable to determine that from the minified scripts. If there's anything we can do in our integration to prevent the loop, we'd be more than happy to improve this!

**Comment by asands1** [comment] 2024-08-05 17:07
Hello! Thank you for your response. If the issue is not happening on your other sites with Mollie components, the issue might be with other plug-ins and themes they have installed. I will ask them to first install these on their staging and see if that solves the issue first.

**Comment by asands1** [comment] 2024-08-06 07:34
Hello, 

I have one additional questions. I do not have access to the plug-in therefore I can not check the settings myself. While we troubleshoot the customer's issue, is there a way to turn off components so that consumers will be redirected to the Mollie Hosted Payment Page for now? Currently, with this merchant, customers can not pay with components.

**Comment by rvdsteege** [comment] 2024-08-07 14:49
To disable Mollie Components, the following code can be added to for example the `functions.php` file of the WordPress theme (there is no setting for this):

```php
add_action(
	'wp_print_scripts',
	function() {
		wp_dequeue_script( 'pronamic-pay-mollie-wc-legacy-checkout' );
	},
	15
);
```

**Comment by remcotolsma** [comment] 2024-09-03 08:21
I will be closing this issue as we are unable to reproduce it and do not have sufficient information at this time to investigate and resolve this further. Should additional information become available, this issue can always be reopened.

**Closed by remcotolsma** 2024-09-03 08:21 UTC
